In [53]:
import pandas as pd 
import matplotlib.pyplot as plt
import scipy.stats as st
import os
pd.set_option('display.max_rows', None)


#path = os.path.join('C:' + os.sep, 'ASG', 'Desktop', 'DataViz', 'glassdoor_data.csv')
glassdoor_data = pd.read_csv(r"C:\Users\ASG\Desktop\DataViz\glassdoor_data.csv")

In [59]:
glassdoor_data.columns

Index(['Unnamed: 0', 'index', 'Job Title', 'Salary Estimate',
       'Job Description', 'Rating', 'Company Name', 'Location', 'Headquarters',
       'Size', 'Founded', 'Type of ownership', 'Industry', 'Sector', 'Revenue',
       'Competitors', 'Easy Apply'],
      dtype='object')

In [54]:
# this chart will show 
types= glassdoor_data['Industry']
industry_type = pd.DataFrame(types)
industry_type.head(3909)

                                      Industry
0                              Travel Agencies
1                    Health, Beauty, & Fitness
2                                           -1
3                                     Internet
4                      Advertising & Marketing
5                           Insurance Carriers
6        Investment Banking & Asset Management
7                                           -1
8      Enterprise Software & Network Solutions
9        Investment Banking & Asset Management
10     Enterprise Software & Network Solutions
11                                    Internet
12     Enterprise Software & Network Solutions
13       Investment Banking & Asset Management
14       Investment Banking & Asset Management
15                     Advertising & Marketing
16                         Other Retail Stores
17                                  Consulting
18                         Other Retail Stores
19                      Research & Development
20    Motion Picture Production & Distribution
21                                    Internet
22                          Brokerage Services
23                                 IT Services
24                     Advertising & Marketing
25                                    Internet
26                Computer Hardware & Software
27                          Insurance Carriers
28                   Health, Beauty, & Fitness
29                          Insurance Carriers
30                                 IT Services
31                Computer Hardware & Software
32                          Brokerage Services
33                           Security Services
34                          Insurance Carriers
35                                    Internet
36                          Casual Restaurants
37                      Food & Beverage Stores
38                          Casual Restaurants
39                             Food Production
40                                          -1
41                          Brokerage Services
42                     Advertising & Marketing
43                                    Internet
44                                          -1
45            Health Fundraising Organizations
46          Home Furniture & Housewares Stores
47                      Research & Development
48              Financial Analytics & Research
49                 Education Training Services
50       Investment Banking & Asset Management
51       Investment Banking & Asset Management
52                                    Internet
53     Enterprise Software & Network Solutions
54                          Insurance Carriers
55                                          -1
56                                  Consulting
57                                    Internet
58                                    Internet
59                                    Internet
60                                    Internet
61                                          -1
62                                    Internet
63                                          -1
64                     Advertising & Marketing
65       Investment Banking & Asset Management
66       Investment Banking & Asset Management
67                     Advertising & Marketing
68                                     Lending
69                                    Internet
70                           Social Assistance
71                                 IT Services
72                     Advertising & Marketing
73                                          -1
74                                    Internet
75                                  Publishing
76                          Brokerage Services
77    Motion Picture Production & Distribution
78                                    Internet
79                                  Consulting
80                            Federal Agencies
81            Health Care Services & Hospitals
82                                          -1
83     Enterprise Software & Network Solutions
84                                    Internet
85                Computer Hardware & Software
86       Investment Banking & Asset Management
87                                    Internet
88                                  Consulting
89                                          -1
90                Computer Hardware & Software
91          Oil & Gas Exploration & Production
92                      Staffing & Outsourcing
93            Health Care Services & Hospitals
94                                 IT Services
95                                          -1
96                         Other Retail Stores
97                         Other Retail Stores
98                                  Consulting
99       Investment Banking & Asset Management
100      Investment Banking & Asset Management
101                                   Internet
102                     Staffing & Outsourcing
103                                 Consulting
104                                   Internet
105                                         -1
106                          Social Assistance
107                     Staffing & Outsourcing
108           Venture Capital & Private Equity
109              Building & Personnel Services
110                     Staffing & Outsourcing
111                    Advertising & Marketing
112                    Advertising & Marketing
113                           Federal Agencies
114                     Food & Beverage Stores
115               Computer Hardware & Software
116                                   Internet
117                                         -1
118    Enterprise Software & Network Solutions
119      Investment Banking & Asset Management
120                                Video Games
121                                IT Services
122           Health Care Services & Hospitals
123                                   Internet
124                                         -1
125                                   Internet
126               Computer Hardware & Software
127      Investment Banking & Asset Management
128                                IT Services
129                                         -1
130                                 Accounting
131                                         -1
132                    Consumer Product Rental
133   Motion Picture Production & Distribution
134                                         -1
135                                   Internet
136                                   Internet
137                Education Training Services
138               Computer Hardware & Software
139                                IT Services
140                                IT Services
141                                 Consulting
142                                         -1
143                                   Internet
144                                IT Services
145                                IT Services
146                                         -1
147              Food & Beverage Manufacturing
148                     Staffing & Outsourcing
149      Investment Banking & Asset Management
150                     Research & Development
151                                         -1
152                                         -1
153                                  Wholesale
154    Enterprise Software & Network Solutions
155                                IT Services
156                    Advertising & Marketing
157                                         -1
158                                   Internet
159                                         -1
160                      Banks & Credit Unions
161                                 Consulting
162           Health Care Services & Hospitals
163            Insurance Agencies & Brokerages
164                    Advertising & Marketing
165                                   Internet
166           Health Care Services & Hospitals
167                      Municipal Governments
168           Health Care Services & Hospitals
169            Insurance Agencies & Brokerages
170                                         -1
171                                Real Estate
172    Enterprise Software & Network Solutions
173                                   Internet
174                                         -1
175           Health Care Services & Hospitals
176               Computer Hardware & Software
177                                         -1
178                                   Internet
179                                         -1
180                                   Internet
181                                   Internet
182                                         -1
183                        Other Retail Stores
184                                         -1
185                                         -1
186                                   Internet
187                                         -1
188                                         -1
189           Health Care Services & Hospitals
190                                   Internet
191                                         -1
192                                   Internet
193                                         -1
194                        Other Retail Stores
195                                   Internet
196                            Food Production
197                                   Internet
198                     Staffing & Outsourcing
199    Enterprise Software & Network Solutions
200                  Health, Beauty, & Fitness
201                    Advertising & Marketing
202                                Video Games
203                                IT Services
204                    Advertising & Marketing
205                         Insurance Carriers
206                  Biotech & Pharmaceuticals
207                     Staffing & Outsourcing
208                         Brokerage Services
209                                         -1
210                        Other Retail Stores
211    Enterprise Software & Network Solutions
212                     Staffing & Outsourcing
213                                   Internet
214                    Advertising & Marketing
215                    Advertising & Marketing
216                                   Internet
217                Commercial Equipment Rental
218                     Staffing & Outsourcing
219                                         -1
220                     Staffing & Outsourcing
221                         Insurance Carriers
222                         Insurance Carriers
223           Health Care Services & Hospitals
224      Investment Banking & Asset Management
225                                         -1
226           Health Care Services & Hospitals
227                                    Lending
228                  Health, Beauty, & Fitness
229                      Banks & Credit Unions
230                     Research & Development
231                                   Internet
232                     Staffing & Outsourcing
233                                   Internet
234                        Other Retail Stores
235                     Staffing & Outsourcing
236      Investment Banking & Asset Management
237                                IT Services
238                                IT Services
239                                    Lending
240   Motion Picture Production & Distribution
241               Computer Hardware & Software
242                         Insurance Carriers
243   Motion Picture Production & Distribution
244                     Staffing & Outsourcing
245                         Casual Restaurants
246                                         -1
247               Computer Hardware & Software
248                    Advertising & Marketing
249                    Advertising & Marketing
250                         Insurance Carriers
251                          Social Assistance
252               Computer Hardware & Software
253                                         -1
254                     Staffing & Outsourcing
255               Computer Hardware & Software
256                                         -1
257            Consumer Products Manufacturing
258                         Insurance Carriers
259                    Advertising & Marketing
260                                   Internet
261                                IT Services
262                                   Internet
263      Investment Banking & Asset Management
264      Investment Banking & Asset Management
265                        Other Retail Stores
266                                   Internet
267                                         -1
268                                Video Games
269               Computer Hardware & Software
270                                         -1
271      Investment Banking & Asset Management
272    Enterprise Software & Network Solutions
273                    Advertising & Marketing
274                                   Internet
275                    Advertising & Marketing
276                                   Internet
277    Enterprise Software & Network Solutions
278             Financial Analytics & Research
279             Financial Analytics & Research
280                                   Internet
281           Health Care Services & Hospitals
282           Health Care Services & Hospitals
283                                IT Services
284      Investment Banking & Asset Management
285                      Banks & Credit Unions
286                           Federal Agencies
287                                   Internet
288                                         -1
289                                IT Services
290      Investment Banking & Asset Management
291                         Brokerage Services
292                     Staffing & Outsourcing
293           Health Care Services & Hospitals
294                        Sports & Recreation
295                            Stock Exchanges
296      Investment Banking & Asset Management
297                     Food & Beverage Stores
298      Investment Banking & Asset Management
299      Investment Banking & Asset Management
300                                         -1
301    Enterprise Software & Network Solutions
302                      Banks & Credit Unions
303                                         -1
304                        Other Retail Stores
305                                         -1
306                                         -1
307                                         -1
308                     Research & Development
309                      Municipal Governments
310                          Social Assistance
311                                IT Services
312                                   Internet
313                    Advertising & Marketing
314                        Other Retail Stores
315                                IT Services
316                                   Internet
317                     Staffing & Outsourcing
318                                         -1
319                    Advertising & Marketing
320                                         -1
321                                IT Services
322                                IT Services
323                                   Internet
324                                IT Services
325               Computer Hardware & Software
326            Insurance Agencies & Brokerages
327                         Insurance Carriers
328                                         -1
329                  Biotech & Pharmaceuticals
330                     Staffing & Outsourcing
331                                         -1
332               Computer Hardware & Software
333               Computer Hardware & Software
334              TV Broadcast & Cable Networks
335                         Brokerage Services
336                                   Internet
337             Financial Analytics & Research
338                                Video Games
339                                 Consulting
340              TV Broadcast & Cable Networks
341                                Video Games
342                                   Internet
343        Department, Clothing, & Shoe Stores
344              TV Broadcast & Cable Networks
345                         Insurance Carriers
346                        Aerospace & Defense
347           Health Care Services & Hospitals
348                     Research & Development
349                     Research & Development
350                     Research & Development
351                                   Internet
352      Investment Banking & Asset Management
353                                   Internet
354                                IT Services
355                                 Consulting
356                                   Internet
357                                   Internet
358                                         -1
359                                Video Games
360                                   Internet
361                           Federal Agencies
362             Financial Analytics & Research
363                                   Internet
364                                IT Services
365                         Brokerage Services
366                                         -1
367      Investment Banking & Asset Management
368               Computer Hardware & Software
369                                IT Services
370                                   Internet
371   Motion Picture Production & Distribution
372                                   Internet
373                                     Energy
374                                         -1
375              TV Broadcast & Cable Networks
376           Health Care Services & Hospitals
377           Health Care Services & Hospitals
378                                   Internet
379                                Real Estate
380               Computer Hardware & Software
381                                         -1
382                                Real Estate
383                               Construction
384                     Staffing & Outsourcing
385                   Logistics & Supply Chain
386    Enterprise Software & Network Solutions
387   Consumer Electronics & Appliances Stores
388      Investment Banking & Asset Management
389                  Biotech & Pharmaceuticals
390                    Advertising & Marketing
391               Computer Hardware & Software
392                     Staffing & Outsourcing
393               Computer Hardware & Software
394                                IT Services
395    Enterprise Software & Network Solutions
396                  Transportation Management
397                                Real Estate
398           Health Care Services & Hospitals
399                          Social Assistance
400                        Other Retail Stores
401               Computer Hardware & Software
402                    Advertising & Marketing
403               Computer Hardware & Software
404                          Social Assistance
405      Investment Banking & Asset Management
406                                   Internet
407                                   Internet
408                                   Internet
409    Enterprise Software & Network Solutions
410                                         -1
411      Investment Banking & Asset Management
412   Motion Picture Production & Distribution
413              TV Broadcast & Cable Networks
414                                         -1
415                                Video Games
416      Investment Banking & Asset Management
417                    Advertising & Marketing
418                                         -1
419    Enterprise Software & Network Solutions
420                                         -1
421                     Staffing & Outsourcing
422                                   Internet
423               Computer Hardware & Software

In [55]:
# finding duplicates 
#industry_type.duplicated(keep=True)

In [62]:
glassdoor_data.loc[glassdoor_data['Industry'] == 'IT Services']

,Unnamed: 0,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply
23,23,23,Senior Data Engineer (Healthcare Domain experi...,$111K-$181K (Glassdoor est.),"Key Responsibilities\n\n- Architect, build, an...",3.4,Enterprise Integration\n3.4,"New York, NY","Jacksonville, FL",51 to 200 employees,1998,Company - Private,IT Services,Information Technology,$25 to $50 million (USD),-1,-1
30,30,32,Data Scientist,$120K-$140K (Glassdoor est.),Caserta is a best-in-class Data Analytics cons...,4.3,Caserta\n4.3,"New York, NY","New York, NY",51 to 200 employees,2001,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,-1,-1
71,71,75,Data Scientist,$119K-$147K (Glassdoor est.),We are building a new kind of financial compan...,3.9,ApTask\n3.9,"New York, NY","Iselin, NJ",201 to 500 employees,2010,Company - Private,IT Services,Information Technology,$50 to $100 million (USD),"Collabera, Mitchell Martin, The Judge Group",-1
94,94,100,Data Scientist,$74K-$124K (Glassdoor est.),Job Description\nPersonalize the experience fo...,2.8,Gate Staffing LLC\n2.8,"New York, NY","East Northport, NY",1 to 50 employees,2010,Self-employed,IT Services,Information Technology,$1 to $5 million (USD),-1,-1
121,121,129,Data Scientist,$102K-$121K (Glassdoor est.),"Hi,\n\nGreetings of the Day!!!\n\nLooking for ...",4.8,TechProjects\n4.8,"New York, NY","North Brunswick, NJ",1 to 50 employees,2011,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,-1,-1
128,128,136,"Data Scientist / Analytics, Data Engineering",$102K-$121K (Glassdoor est.),"Consultant, Data Science (GenPact/Morgan Stanl...",1.0,Sphinix Solutions\n1.0,"New York, NY","New York, NY",1 to 50 employees,-1,Company - Private,IT Services,Information Technology,Less than $1 million (USD),-1,-1
139,139,149,Data Scientist,$129K-$210K (Glassdoor est.),Duties Provides advanced professional input to...,3.4,"Digital Intelligence Systems, LLC\n3.4","Franklin Lakes, NJ","Mc Lean, VA",1001 to 5000 employees,1994,Company - Private,IT Services,Information Technology,$100 to $500 million (USD),-1,-1
140,140,150,"Senior Analyst, Data Science",$129K-$210K (Glassdoor est.),The Role:\n\nRoku is looking for a Senior Anal...,3.9,Roku\n3.9,"New York, NY","San Jose, CA",1001 to 5000 employees,2002,Company - Public,IT Services,Information Technology,$500 million to $1 billion (USD),-1,-1
144,144,154,Quantitative Researcher - Portfolio Modeling,$129K-$210K (Glassdoor est.),Are you a Quantitative Researcher that has exp...,-1.0,Edward Daniels Group,"New York, NY","New York, NY",1 to 50 employees,2007,Company - Private,IT Services,Information Technology,$1 to $5 million (USD),-1,-1
145,145,155,Data Scientist,$129K-$210K (Glassdoor est.),Job Title: Data Scientist\n\nLocation: New Jer...,4.8,InvenTech Info\n4.8,"Jersey City, NJ","Bengaluru, India",201 to 500 employees,2010,Company - Private,IT Services,Information Technology,$1 to $5 million (USD),-1,-1
155,155,165,Data Scientist - Leading Quant Hedge Fund,$129K-$210K (Glassdoor est.),Are you a Data Scientist that is interested in...,-1.0,Edward Daniels Group,"New York, NY","New York, NY",1 to 50 employees,2007,Company - Private,IT Services,Information Technology,$1 to $5 million (USD),-1,-1
203,203,217,Machine Learning Engineer,$119K-$147K (Glassdoor est.),"Machine Learning Engineer\n\nAt Temboo, we bui...",3.9,Temboo\n3.9,"New York, NY","New York, NY",1 to 50 employees,-1,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,-1,-1
237,237,264,Quantum Data Scientist (Industrial-Process sec...,$116K-$152K (Glassdoor est.),"Introduction\nAs a Data Scientist at IBM, you ...",3.7,IBM\n3.7,"New York, NY","Armonk, NY",10000+ employees,1911,Company - Public,IT Services,Information Technology,$10+ billion (USD),"Amazon, Accenture, Microsoft",-1
238,238,265,Principal Data Scientist,$116K-$152K (Glassdoor est.),Caserta is a best-in-class Data Analytics cons...,4.3,Caserta\n4.3,"New York, NY","New York, NY",51 to 200 employees,2001,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,-1,-1
261,261,313,Data Analyst Intern,$110K-$139K (Glassdoor est.),The hiring company is one of the world's large...,3.6,My Job Tank\n3.6,"Jersey City, NJ","New York, NY",51 to 200 employees,-1,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,-1,TRUE
283,283,343,Data Analyst,$82K-$141K (Glassdoor est.),About Tachyon Technologies:\n\nTachyon Technol...,4.4,Tachyon Technologies\n4.4,"New York, NY","Irving, TX",201 to 500 employees,2011,Company - Private,IT Services,Information Technology,$10 to $25 million (USD),-1,-1
289,289,351,Sr Data Scientist,$82K-$141K (Glassdoor est.),Senior Data Scientist Description The Senior D...,3.6,Hadiamondstar Software Solutions LLC\n3.6,"Jersey City, NJ","Fairfax, VA",1 to 50 employees,-1,Company - Private,IT Services,Information Technology,$1 to $5 million (USD),-1,-1
311,311,376,Senior Data Scientist,$96K-$119K (Glassdoor est.),"Senior Data Scientist\n\nNewark, NJ, United St...",4.0,ASB Resources\n4.0,"Newark, NJ","Princeton, NJ",1 to 50 employees,2004,Company - Private,IT Services,Information Technology,$1 to $5 million (USD),-1,-1
315,315,383,"Data Scientist with SQL, Python, R, Tableau",$96K-$119K (Glassdoor est.),"Greetings of the day, I am Shravya working as ...",4.8,TechProjects\n4.8,"New York, NY","North Brunswick, NJ",1 to 50 employees,2011,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,-1,-1
321,321,389,Quantum Principal Data Scientist (Industrial-D...,$96K-$119K (Glassdoor est.),"Introduction\nAs a Data Scientist at IBM, you ...",3.7,IBM\n3.7,"New York, NY","Armonk, NY",10000+ employees,1911,Company - Public,IT Services,Information Technology,$10+ billion (USD),"Amazon, Accenture, Microsoft",-1
322,322,390,Quantum Principal Data Scientist (Industrial-P...,$96K-$119K (Glassdoor est.),"Introduction\nAs a Data Scientist at IBM, you ...",3.7,IBM\n3.7,"New York, NY","Armonk, NY",10000+ employees,1911,Company - Public,IT Services,Information Technology,$10+ billion (USD),"Amazon, Accenture, Microsoft",-1
324,324,392,Senior Data Scientist,$96K-$119K (Glassdoor est.),Job Description\nTitle: Senior Data Scientist\...,3.7,Sunrise Systems Inc\n3.7,"Newark, NJ","Edison, NJ",501 to 1000 employees,1990,Company - Private,IT Services,Information Technology,$25 to $50 million (USD),-1,-1
354,354,422,Data Scientist,$102K-$164K (Glassdoor est.),In this role you will join the Aviana Data Sci...,4.2,Aviana Global Technologies\n4.2,"Brea, CA","Brea, CA",1 to 50 employees,1994,Company - Private,IT Services,Information Technology,$10 to $25 million (USD),"OpenSymmetry, Perficient, DataClarity",-1
364,364,433,Data Scientist,$113K-$180K (Glassdoor est.),Our entertainment company is seeking a Data Sc...,-1.0,Evolvinc,"Burbank, CA","Los Angeles, CA",1 to 50 employees,2005,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,-1,-1
369,369,438,Data Engineer,$113K-$180K (Glassdoor est.),Join SADA as a Data Engineer!\n\nYour Mission\...,4.7,SADA\n4.7,"Los Angeles, CA","North Hollywood, CA",51 to 200 employees,2000,Company - Private,IT Services,Information Technology,$50 to $100 million (USD),-1,-1
394,394,464,Quantum Data Scientist (Industrial-Process sec...,$113K-$180K (Glassdoor est.),"Introduction\nAs a Data Scientist at IBM, you ...",3.7,IBM\n3.7,"Los Angeles, CA","Armonk, NY",10000+ employees,1911,Company - Public,IT Services,Information Technology,$10+ billion (USD),"Amazon, Accenture, Microsoft",-1
427,427,497,Scientist,$76K-$122K (Glassdoor est.),Job Description\nPosition Overview\n\nScientis...,3.7,CodeForce 360\n3.7,"Los Angeles, CA","Alpharetta, GA",51 to 200 employees,2010,Company - Private,IT Services,Information Technology,$25 to $50 million (USD),-1,-1
449,449,519,Senior Data Engineer/Data Scientist,$76K-$122K (Glassdoor est.),We are a recruiting agency that works hard to ...,-1.0,Evolvinc,"Burbank, CA","Los Angeles, CA",1 to 50 employees,2005,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,-1,-1
463,463,533,Principal Data Scientist- Public Sector,$134K-$218K (Glassdoor est.),"*Introduction**As a Data Scientist at IBM, you...",3.7,IBM\n3.7,"Los Angeles, CA","Armonk, NY",10000+ employees,1911,Company - Public,IT Services,Information Technology,$10+ billion (USD),"Amazon, Accenture, Microsoft",-1
473,473,543,Junior Data Analyst,$134K-$218K (Glassdoor est.),Job Description\nJob description\nInterpret da...,5.0,"Staffigo Technical Services, LLC\n5.0","Los Angeles, CA","Woodridge, IL",51 to 200 employees,2008,Company - Private,IT Services,Information Technology,$50 to $100 million (USD),-1,-1
475,475,545,Quantum Principal Data Scientist (Industrial-D...,$134K-$218K (Glassdoor est.),"*Introduction**As a Data Scientist at IBM, you...",3.7,IBM\n3.7,"Los Angeles, CA","Armonk, NY",10000+ employees,1911,Company - Public,IT Services,Information Technology,$10+ billion (USD),"Amazon, Accenture, Microsoft",-1
489,489,559,Data Analyst,$76K-$125K (Glassdoor est.),"Data Analyst Location Glendale, CA Duration 3 ...",3.7,"iSpace, Inc\n3.7","Glendale, CA","El Segundo, CA",51 to 200 employees,2000,Company - Private,IT Services,Information Technology,$5 to $10 million (USD),Cyient,-1
505,505,575,Microsoft Analytics Consultant,$76K-$125K (Glassdoor est.),"Introduction\nAs an IBM consultant, you direct...",3.7,IBM\n3.7,"Los Angeles, CA","Armonk, NY",10000+ employees,1911,Company - Public,IT Services,Information Technology,$10+ billion (USD),"Amazon, Accenture, Microsoft",-1
513,513,583,Quantum Principal Data Scientist (Industrial-P...,$132K-$208K (Glassdoor est.),"Introduction\nAs a Data Scientist at IBM, you ...",3.7,IBM\n3.7,"Los Angeles, CA","Armonk, NY",10000+ employees,1911,Company - Public,IT Services,Information Technology,$10+ billion (USD),"Amazon, Accenture, Microsoft",-1
521,521,591,Data Modeler,$132K-$208K (Glassdoor est.),Role: Data Modeler\n\nDuration: 6 months\n\nLo...,4.0,Kairos Technologies\n4.0,"Los Angeles, CA","Irving, TX",51 to 200 employees,2003,Company - Private,IT Services,Information Technology,$5 to $10 million (USD),-1,-1
525,525,595,"Scientist 2, Data Analytics",$132K-$208K (Glassdoor est.),"AretÃ© Associates seeks highly motivated, tech...",4.4,Arete Associates Inc\n4.4,"Northridge, CA","Rolling Meadows, IL",51 to 200 employees,2008,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,-1,-1
531,531,601,Data Analyst,$132K-$208K (Glassdoor est.),Job Description\nJob description\nInterpret da...,5.0,"Staffigo Technical Services, LLC\n5.0","Los Angeles, CA","Woodridge, IL",51 to 200 employees,2008,Company - Private,IT Services,Information Technology,$50 to $100 million (USD),-1,-1
535,535,605,Data Analyst,$132K-$208K (Glassdoor est.),Our client is looking to hire an experienced f...,-1.0,Eleven Recruiting - CHURN,"Los Angeles, CA","Los Angeles, CA",1 to 50 employees,-1,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,-1,-1
536,536,606,Data Analyst,$132K-$208K (Glassdoor est.),DatamanUSA LLC has an exciting opportunity for...,3.4,DatamanUSA\n3.4,"Los Angeles, CA","Centennial, CO",51 to 200 employees,-1,Company - Private,IT Services,Information Technology,$5 to $10 million (USD),-1,-1
540,540,610,Microsoft Dynamics CRM Data Analyst,$132K-$208K (Glassdoor est.),*Introduction**As an IBM Application Architect...,3.7,IBM\n3.7,"Los Angeles, CA","Armonk, NY",10000+ employees,1911,Company - Public,IT Services,Information Technology,$10+ billion (USD),"Amazon, Accenture, Microsoft",-1
549,549,619,Data Engineer,$83K-$105K (Glassdoor est.),Job Description\nOur client is looking for a S...,4.0,Prosum\n4.0,"Los Angeles, CA","El Segundo, CA",201 to 500 employees,1996,Company - Private,IT Services,Information Technology,$25 to $50 million (USD),"Kforce, NTT DATA, IBM",-1
558,558,628,Sr Data Engineer (AWS),$83K-$105K (Glassdoor est.),This role will start out as 100 remote until c...,4.0,Prosum\n4.0,"Los Angeles, CA","El Segundo, CA",201 to 500 employees,1996,Company - Private,IT Services,Information Technology,$25 to $50 million (USD),"Kforce, NTT DATA, IBM",-1
562,562,632,Data Engineer,$83K-$105K (Glassdoor est.),Job Description\nOur entertainment company is ...,-1.0,EvolvInc,"Burbank, CA","Los Angeles, CA",1 to 50 employees,2005,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,-1,-1
564,564,634,Data Engineer,$83K-$105K (Glassdoor est.),"Role Data Engineer Location Sherman Oaks, CA D...",4.8,Agilisium LLC\n4.8,"Los Angeles, CA","Westlake Village, CA",201 to 500 employees,2012,Company - Private,IT Services,Information Technology,$10 to $25 million (USD),-1,-1
572,572,642,Data Engineer - W2 only - Local to Los Angeles...,$83K-$105K (Glassdoor est.),Position- Sr Data Engineer\n\nLocation- Los An...,4.1,BayOne Solutions\n4.1,"Los Angeles, CA","Pleasanton, CA",1001 to 5000 employees,-1,Company - Private,IT Services,Information Technology,$5 to $10 million (USD),-1,-1
576,576,650,Business Intelligence Analyst,$75K-$143K (Glassdoor est.),"Job Description\nDevelop, test, Quality Assura...",3.1,Systech Business Solutions\n3.1,"Glendale, CA","Glendale, CA",201 to 500 employees,1993,Company - Private,IT Services,Information Technology,$25 to $50 million (USD),-1,-1
608,608,705,"Machine Learning Engineer, Signal Processing",$37K-$75K (Glassdoor est.),"Machine Learning Engineer, Signal Processing\n...",5.0,NxT Level\n5.0,"Torrance, CA","Tacoma, WA",1 to 50 employees,2017,Company - Private,IT Services,Information Technology,$1 to $5 million (USD),-1,-1
628,628,733,Business Intelligence Analyst Tableau From Scr...,$113K-$184K (Glassdoor est.),Job Description\nSurround yourself with friend...,2.8,Camden Kelly Corporation\n2.8,"Los Angeles, CA","Dallas, TX",1 to 50 employees,2013,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,-1,-1
648,648,754,Business Intelligence Analyst,$113K-$184K (Glassdoor est.),Meet REVOLVE:\n\nREVOLVE is the next-generatio...,3.4,"EMINENT, INC.\n3.4","Cerritos, CA","Williamsville, NY",1 to 50 employees,-1,Company - Private,IT Services,Information Technology,$1 to $5 million (USD),-1,-1
661,661,768,Sr Data Analyst (DW),$136K-$164K (Glassdoor est.),Job Description\nOur client in the Los Angeles...,4.2,"Aviana Global Technologies, Inc\n4.2","Los Angeles, CA","Brea, CA",1 to 50 employees,1994,Company - Private,IT Services,Information Technology,$10 to $25 million (USD),"OpenSymmetry, Perficient, DataClarity",-1
673,673,781,Laboratory Technician/Scientist Molecular Biol...,$136K-$164K (Glassdoor est.),Job Description\nJob description:\n\nWe are lo...,-1.0,EvolvInc,"Carson, CA","Los Angeles, CA",1 to 50 employees,2005,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,-1,-1
676,676,784,Data Analyst Junior,$136K-$164K (Glassdoor est.),Job Description\nJob description\nInterpret da...,5.0,"Staffigo Technical Services, LLC\n5.0","Los Angeles, CA","Woodridge, IL",51 to 200 employees,2008,Company - Private,IT Services,Information Technology,$50 to $100 million (USD),-1,-1
721,721,829,Data Scientist,$46K-$80K (Glassdoor est.),Hi Greetings from Photon!!!!!!! We are looking...,3.0,Photon Infotech\n3.0,"Chicago, IL","Chennai, India",1001 to 5000 employees,1999,Company - Private,IT Services,Information Technology,$100 to $500 million (USD),-1,-1
726,726,835,Data Scientist,$79K-$130K (Glassdoor est.),"Goby Inc seeks a Data Scientist in Chicago, IL...",-1.0,Goby Inc,"Chicago, IL","New York, NY",1 to 50 employees,-1,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,-1,-1
731,731,840,Data Scientist,$79K-$130K (Glassdoor est.),Description\n\n\nDo you want to work at the fo...,4.7,Capax Global\n4.7,"Chicago, IL","Chicago, IL",51 to 200 employees,1998,Subsidiary or Business Segment,IT Services,Information Technology,$25 to $50 million (USD),-1,-1
735,735,844,Data Scientist,$79K-$130K (Glassdoor est.),Job Description\nRole : Data Scientist\n\nLoca...,4.0,Fisec Global\n4.0,"Chicago, IL","San Francisco, CA",1 to 50 employees,-1,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,-1,-1
737,737,846,Data Scientist,$79K-$130K (Glassdoor est.),"Job Description\nData Scientist, Chicago, IL\n...",2.6,Saggezza\n2.6,"Chicago, IL","Chicago, IL",501 to 1000 employees,2006,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,-1,-1
744,744,853,Data Scientist,$79K-$130K (Glassdoor est.),Job Description\nBCforward is seeking a highly...,2.8,BCforward\n2.8,"Chicago, IL","Indianapolis, IN",1001 to 5000 employees,1998,Company - Private,IT Services,Information Technology,Less than $1 million (USD),-1,-1
747,747,856,Data Engineer,$79K-$130K (Glassdoor est.),Join SADA as a Data Engineer!\n\nYour Mission\...,4.7,SADA\n4.7,"Chicago, IL","North Hollywood, CA",51 to 200 employees,2000,Company - Private,IT Services,Information Technology,$50 to $100 million (USD),-1,-1
764,764,873,Data Scientist,$91K-$105K (Glassdoor est.),Domain Experience:\n\n3+ years-experience in m...,4.7,Unicom Technologies INC\n4.7,"Chicago, IL","Naperville, IL",51 to 200 employees,-1,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,-1,-1
776,776,885,Quantum Data Scientist (Industrial-Process sec...,$91K-$105K (Glassdoor est.),"Introduction\nAs a Data Scientist at IBM, you ...",3.7,IBM\n3.7,"Chicago, IL","Armonk, NY",10000+ employees,1911,Company - Public,IT Services,Information Technology,$10+ billion (USD),"Amazon, Accenture, Microsoft",-1
812,812,921,Business Intelligence Analyst,$39K-$81K (Glassdoor est.),Job Description\nWho We Are:\n\nWe believe a w...,3.4,Fooda\n3.4,"Chicago, IL","Chicago, IL",201 to 500 employees,2011,Company - Private,IT Services,Information Technology,Less than $1 million (USD),-1,-1
821,821,930,Senior Data Scientist,$39K-$81K (Glassdoor est.),Numerator is looking for Sr. Data Scientists t...,3.9,Numerator\n3.9,"Chicago, IL","Chicago, IL",1001 to 5000 employees,2004,Company - Private,IT Services,Information Technology,$100 to $500 million (USD),"Nielsen, Kantar, IRI",-1
822,822,931,Workday Data Consultant,$39K-$81K (Glassdoor est.),Collaborative Solutions is a leading global Fi...,3.7,Collaborative Solutions\n3.7,"Chicago, IL","Reston, VA",501 to 1000 employees,2003,Company - Private,IT Services,Information Technology,$50 to $100 million (USD),"Meteorix, OneSource Virtual, DayNine Consulting",-1
832,832,941,Principal Data Scientist- Public Sector,$39K-$81K (Glassdoor est.),"*Introduction**As a Data Scientist at IBM, you...",3.7,IBM\n3.7,"Chicago, IL","Armonk, NY",10000+ employees,1911,Company - Public,IT Services,Information Technology,$10+ billion (USD),"Amazon, Accenture, Microsoft",-1
836,836,945,Data Analyst,$39K-$81K (Glassdoor est.),Senior AWS Developer\n\nUST Global is looking ...,4.1,UST Global\n4.1,"Chicago, IL","Aliso Viejo, CA",10000+ employees,1999,Company - Private,IT Services,Information Technology,$1 to $2 billion (USD),"Cognizant Technology Solutions, Infosys, Wipro",-1
840,840,949,Data Analyst,$39K-$81K (Glassdoor est.),"Role: Data Analyst\nLocation: Chicago, IL(Loca...",3.9,Diverse Lynx\n3.9,"Chicago, IL","Princeton, NJ",501 to 1000 employees,2002,Company - Private,IT Services,Information Technology,$100 to $500 million (USD),-1,-1
846,846,955,Junior Data Analyst,$99K-$174K (Glassdoor est.),Job Description\nJob duties/description\nInter...,5.0,"Staffigo Technical Services, LLC\n5.0","Chicago, IL","Woodridge, IL",51 to 200 employees,2008,Company - Private,IT Services,Information Technology,$50 to $100 million (USD),-1,-1

In [63]:
glassdoor_data.loc[glassdoor_data['Industry'] == 'Staffing & Outsourcing']

,Unnamed: 0,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply
92,92,98,Data Scientist - Altdata,$74K-$124K (Glassdoor est.),Data Scientist - Altdata\n\nLocation: New York...,3.3,Huxley\n3.3,"New York, NY","London, United Kingdom",201 to 500 employees,1995,Company - Private,Staffing & Outsourcing,Business Services,$25 to $50 million (USD),-1,-1
102,102,108,Data Scientist,$74K-$124K (Glassdoor est.),We are the most sought after hedge fund in New...,5.0,Averity\n5.0,"New York, NY","New York, NY",1 to 50 employees,2014,Company - Private,Staffing & Outsourcing,Business Services,Unknown / Non-Applicable,-1,-1
107,107,115,Data Scientist / Statistician,$102K-$121K (Glassdoor est.),Job title: Data Scientist / Statistician\nJob ...,4.2,NJF Global Holdings\n4.2,"New York, NY","London, United Kingdom",51 to 200 employees,2003,Company - Private,Staffing & Outsourcing,Business Services,$10 to $25 million (USD),-1,TRUE
110,110,118,Data Scientist,$102K-$121K (Glassdoor est.),Description\n\nWe are looking for several of t...,4.0,OneWire\n4.0,"New York, NY","New York, NY",1 to 50 employees,2007,Company - Private,Staffing & Outsourcing,Business Services,$1 to $5 million (USD),-1,-1
148,148,158,Data Scientist(s)/Machine Learning Engineer,$129K-$210K (Glassdoor est.),Company: AI/Data Science\nLocation: New York C...,5.0,Blue Horizon Tek Solutions\n5.0,"New York, NY","Coconut Creek, FL",1 to 50 employees,1987,Company - Private,Staffing & Outsourcing,Business Services,Unknown / Non-Applicable,-1,-1
198,198,212,Scientist Data Analytics,$119K-$147K (Glassdoor est.),Title: Scientist Data Analytics\nJob ID: BM765...,4.7,TEEMA\n4.7,"New York, NY","Litchfield Park, AZ",201 to 500 employees,2008,Company - Private,Staffing & Outsourcing,Business Services,$50 to $100 million (USD),-1,-1
207,207,221,Data Science and Analytics,$119K-$147K (Glassdoor est.),Title: Data Science and Analytics\n\nLocation:...,4.0,Two95 International Inc.\n4.0,"New York, NY","Cherry Hill, NJ",1 to 50 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,$1 to $5 million (USD),-1,-1
212,212,226,Data Scientist/Python Developer,$119K-$147K (Glassdoor est.),Looking for a Senior Data Scientist/Python Dev...,3.5,"EDP World, Inc.\n3.5","New York, NY","New York, NY",1 to 50 employees,1968,Company - Private,Staffing & Outsourcing,Business Services,$1 to $5 million (USD),-1,-1
218,218,232,Senior Data Scientist,$119K-$147K (Glassdoor est.),"Job Description\nWould you, as a Senior Data S...",5.0,Averity\n5.0,"New York, NY","New York, NY",1 to 50 employees,2014,Company - Private,Staffing & Outsourcing,Business Services,Unknown / Non-Applicable,-1,-1
220,220,234,Senior Data Scientist,$119K-$147K (Glassdoor est.),Senior Data Scientist\nIf you are a Senior Dat...,4.2,CyberCoders\n4.2,"New York, NY","Irvine, CA",201 to 500 employees,1999,Subsidiary or Business Segment,Staffing & Outsourcing,Business Services,$100 to $500 million (USD),-1,-1
232,232,255,Data Scientist (Fintech),$116K-$152K (Glassdoor est.),Our client is a series A funded fintech startu...,5.0,ingenium.agency\n5.0,"Brooklyn, NY","New York, NY",1 to 50 employees,2016,Company - Private,Staffing & Outsourcing,Business Services,$1 to $5 million (USD),-1,-1
235,235,262,Quantitative Researcher,$116K-$152K (Glassdoor est.),Job title: Quantitative Researcher\nJob type: ...,4.2,NJF Global Holdings\n4.2,"New York, NY","London, United Kingdom",51 to 200 employees,2003,Company - Private,Staffing & Outsourcing,Business Services,$10 to $25 million (USD),-1,TRUE
244,244,273,Quantitative Researcher,$133K-$171K (Glassdoor est.),The Senior Quantitative Researcher will join a...,5.0,LaBine & Associates\n5.0,"New York, NY","San Mateo, CA",1 to 50 employees,2013,Company - Private,Staffing & Outsourcing,Business Services,Unknown / Non-Applicable,-1,-1
254,254,301,Senior Data Scientist,$133K-$171K (Glassdoor est.),"Senior Data Scientist\n\nLocation: New York, U...",3.3,Huxley\n3.3,"New York, NY","London, United Kingdom",201 to 500 employees,1995,Company - Private,Staffing & Outsourcing,Business Services,$25 to $50 million (USD),-1,-1
292,292,354,Machine Learning Engineer,$82K-$141K (Glassdoor est.),"Machine Learning Engineer\nOur client, one of ...",4.1,Mitchell Martin\n4.1,"New York, NY","New York, NY",501 to 1000 employees,1984,Company - Private,Staffing & Outsourcing,Business Services,$100 to $500 million (USD),-1,-1
317,317,385,Machine Learning Scientist,$96K-$119K (Glassdoor est.),My client seeks a Machine Learning Scientist t...,4.7,Job Juncture\n4.7,"Maywood, NJ","Houston, TX",1001 to 5000 employees,1992,Company - Private,Staffing & Outsourcing,Business Services,Less than $1 million (USD),-1,-1
330,330,398,Data Analyst,$146K-$175K (Glassdoor est.),Non-Exempt*\nSchedule: Can be 8a.m. â€“ 5p.m. ...,2.9,"Nesco Resource, LLC\n2.9","New York, NY","Cleveland, OH",1001 to 5000 employees,1956,Company - Private,Staffing & Outsourcing,Business Services,$500 million to $1 billion (USD),-1,-1
384,384,453,Data Analyst,$113K-$180K (Glassdoor est.),"Job Description\nWe hiring a Data Analyst, for...",-1.0,People Tree,"Hermosa Beach, CA","Hermosa Beach, CA",1 to 50 employees,2013,Self-employed,Staffing & Outsourcing,Business Services,Unknown / Non-Applicable,-1,-1
392,392,462,"Chief Data/BI Scientist - SQL, Python/R, Spark...",$113K-$180K (Glassdoor est.),"Chief Data/BI Scientist - SQL, Python/R, Spark...",4.2,CyberCoders\n4.2,"Santa Monica, CA","Irvine, CA",201 to 500 employees,1999,Subsidiary or Business Segment,Staffing & Outsourcing,Business Services,$100 to $500 million (USD),-1,-1
421,421,491,Data Analyst,$113K-$180K (Glassdoor est.),"Title: Data Analyst\nLocation: Chatsworth, CA\...",4.5,HireTalent\n4.5,"Los Angeles, CA","New York, NY",201 to 500 employees,1997,Company - Private,Staffing & Outsourcing,Business Services,$25 to $50 million (USD),-1,-1
425,425,495,Sr. Data Scientist,$76K-$122K (Glassdoor est.),Data Scientist needed for an AI technology com...,4.9,Jobot\n4.9,"Los Angeles, CA","Irvine, CA",51 to 200 employees,2018,Company - Private,Staffing & Outsourcing,Business Services,$25 to $50 million (USD),-1,-1
432,432,502,Machine Learning Engineer,$76K-$122K (Glassdoor est.),Title: Machine Learning Engineer\nJob ID: SM49...,4.7,TEEMA\n4.7,"Los Angeles, CA","Litchfield Park, AZ",201 to 500 employees,2008,Company - Private,Staffing & Outsourcing,Business Services,$50 to $100 million (USD),-1,-1
438,438,508,Data Engineer,$76K-$122K (Glassdoor est.),Position: Data Engineer\n\nReason Open: Has a ...,3.8,Mondo\n3.8,"Los Angeles, CA","New York, NY",51 to 200 employees,2000,Company - Private,Staffing & Outsourcing,Business Services,$100 to $500 million (USD),"Robert Half, Insight Global",-1
441,441,511,NLP Engineer -Data Scientist,$76K-$122K (Glassdoor est.),Direct End Client: Medtronic\n<strong>Job Titl...,3.4,V Group Inc.\n3.4,"Northridge, CA","Louisville, KY",501 to 1000 employees,1997,Company - Private,Staffing & Outsourcing,Business Services,$100 to $500 million (USD),-1,-1
451,451,521,Associate Scientist,$76K-$122K (Glassdoor est.),Kelly ServicesÂ® has been providing outstandin...,3.4,Kelly\n3.4,"Santa Monica, CA","Troy, MI",5001 to 10000 employees,1946,Company - Public,Staffing & Outsourcing,Business Services,$5 to $10 billion (USD),"Adecco, ManpowerGroup, Allegis Corporation",-1
464,464,534,Business Intelligence Analyst - Entry,$134K-$218K (Glassdoor est.),"Business Intelligence Analyst - Los Angeles, C...",3.8,Enterprise Solutions Inc\n3.8,"Los Angeles, CA","Naperville, IL",51 to 200 employees,2000,Company - Private,Staffing & Outsourcing,Business Services,$25 to $50 million (USD),-1,-1
483,483,553,Data Engineer,$76K-$125K (Glassdoor est.),Title: Data Engineer\nJob ID: TJ3682741021\nLo...,4.7,TEEMA\n4.7,"Los Angeles, CA","Litchfield Park, AZ",201 to 500 employees,2008,Company - Private,Staffing & Outsourcing,Business Services,$50 to $100 million (USD),-1,-1
487,487,557,Data Scientist,$76K-$125K (Glassdoor est.),Data Scientist\nIf you are a Data Scientist wi...,4.2,CyberCoders\n4.2,"El Segundo, CA","Irvine, CA",201 to 500 employees,1999,Subsidiary or Business Segment,Staffing & Outsourcing,Business Services,$100 to $500 million (USD),-1,-1
495,495,565,Associate Scientist,$76K-$125K (Glassdoor est.),Job Description\n\n\nJob #: 1073430\n\nSeeking...,3.8,Apex Systems\n3.8,"Los Angeles, CA","Glen Allen, VA",1001 to 5000 employees,1995,Subsidiary or Business Segment,Staffing & Outsourcing,Business Services,$2 to $5 billion (USD),"TEKsystems, Insight Global, Accenture",TRUE
497,497,567,Data Analyst,$76K-$125K (Glassdoor est.),"Data Analyst Location Burbank, CA Start Date J...",4.3,"ConsultNet, LLC\n4.3","Burbank, CA","South Jordan, UT",201 to 500 employees,1996,Company - Private,Staffing & Outsourcing,Business Services,$50 to $100 million (USD),-1,-1
506,506,576,Data Engineer,$76K-$125K (Glassdoor est.),Data Engineer\n\nBigtime Entertainment Co. bui...,5.0,ingenium.agency\n5.0,"Los Angeles, CA","New York, NY",1 to 50 employees,2016,Company - Private,Staffing & Outsourcing,Business Services,$1 to $5 million (USD),-1,-1
522,522,592,Data Analyst,$132K-$208K (Glassdoor est.),Description FOR IMMEDIATE CONSIDERATION email ...,3.5,Robert Half\n3.5,"El Segundo, CA","Menlo Park, CA",10000+ employees,1948,Company - Public,Staffing & Outsourcing,Business Services,$2 to $5 billion (USD),"Adecco, Manpower",-1
528,528,598,"Instructor, Data Scientist",$132K-$208K (Glassdoor est.),Data Scientist Instructor\n\nThis Jobot Job is...,4.9,Jobot\n4.9,"Los Angeles, CA","Irvine, CA",51 to 200 employees,2018,Company - Private,Staffing & Outsourcing,Business Services,$25 to $50 million (USD),-1,-1
555,555,625,Data Analyst,$83K-$105K (Glassdoor est.),"Location: Sunnyvale, CAPosition Overview:\n\nD...",3.6,ICONMA\n3.6,"Culver City, CA","Troy, MI",1001 to 5000 employees,2000,Company - Private,Staffing & Outsourcing,Business Services,$100 to $500 million (USD),Experis,-1
563,563,633,Data Engineer,$83K-$105K (Glassdoor est.),Data Engineer\nIf you are a Data Engineer look...,4.2,CyberCoders\n4.2,"Pasadena, CA","Irvine, CA",201 to 500 employees,1999,Subsidiary or Business Segment,Staffing & Outsourcing,Business Services,$100 to $500 million (USD),-1,-1
566,566,636,Machine Learning Engineer,$83K-$105K (Glassdoor est.),Machine Learning Engineer\nIf you are a Machin...,4.2,CyberCoders\n4.2,"Calabasas, CA","Irvine, CA",201 to 500 employees,1999,Subsidiary or Business Segment,Staffing & Outsourcing,Business Services,$100 to $500 million (USD),-1,-1
609,609,708,Survey Data Analyst,$37K-$75K (Glassdoor est.),Job Description\nSurvey Data Analyst\nOverview...,4.9,Cypress HCM\n4.9,"Los Angeles, CA","Walnut Creek, CA",51 to 200 employees,2005,Company - Private,Staffing & Outsourcing,Business Services,Unknown / Non-Applicable,-1,-1
630,630,736,Associate Scientist I - Analytical Ops,$113K-$184K (Glassdoor est.),"Contractor, Analytical Ops\n\nKnowledge Manage...",3.1,"Integrated Resources, Inc\n3.1","Santa Monica, CA","Edison, NJ",201 to 500 employees,1996,Company - Private,Staffing & Outsourcing,Business Services,$25 to $50 million (USD),-1,-1
631,631,737,Data Analyst / Developer,$113K-$184K (Glassdoor est.),RESPONSIBILITIES:\n\nKforce has a client in se...,4.1,Kforce\n4.1,"Los Angeles, CA","Tampa, FL",10000+ employees,1966,Company - Public,Staffing & Outsourcing,Business Services,$1 to $2 billion (USD),-1,-1
642,642,748,Associate Scientist - Sensory - Jr (Daily/Week...,$113K-$184K (Glassdoor est.),Job Description\n\n\nJob #: 1076379\n\nSensory...,3.8,Apex Systems\n3.8,"Torrance, CA","Glen Allen, VA",1001 to 5000 employees,1995,Subsidiary or Business Segment,Staffing & Outsourcing,Business Services,$2 to $5 billion (USD),"TEKsystems, Insight Global, Accenture",TRUE
657,657,763,Sr. Data Analyst,$136K-$164K (Glassdoor est.),"Sr. Data Analyst Location Burbank, CA Start Da...",4.3,"ConsultNet, LLC\n4.3","Burbank, CA","South Jordan, UT",201 to 500 employees,1996,Company - Private,Staffing & Outsourcing,Business Services,$50 to $100 million (USD),-1,-1
669,669,776,Senior Customer Data Analyst : 20,$136K-$164K (Glassdoor est.),Job Description\nPrimary Skills: Data Analysis...,4.6,Akraya Inc.\n4.6,"Los Angeles, CA","Santa Clara, CA",51 to 200 employees,2001,Company - Private,Staffing & Outsourcing,Business Services,$25 to $50 million (USD),"Collabera, Artech Information Systems, TEKsystems",-1
679,679,787,"Scientist I, Manufacturing Sciences - West Hills",$136K-$164K (Glassdoor est.),Job Description\nAdvantage Resourcing is seeki...,2.7,Advantage Resourcing\n2.7,"Los Angeles, CA","Cincinnati, OH",10000+ employees,1969,Company - Private,Staffing & Outsourcing,Business Services,$1 to $2 billion (USD),"Randstad US, Robert Half, Allegis Group",-1
745,745,854,Data Scientist,$79K-$130K (Glassdoor est.),Job Description\nIllinois insurer is looking t...,4.2,DW Simpson\n4.2,"Chicago, IL","Chicago, IL",51 to 200 employees,1989,Company - Private,Staffing & Outsourcing,Business Services,$10 to $25 million (USD),-1,-1
751,751,860,Product Data Analyst,$79K-$130K (Glassdoor est.),"Role: Product Data Analyst\nLocation: Chicago,...",3.8,Mondo\n3.8,"Chicago, IL","New York, NY",51 to 200 employees,2000,Company - Private,Staffing & Outsourcing,Business Services,$100 to $500 million (USD),"Robert Half, Insight Global",-1
752,752,861,Senior Data Scientist,$91K-$105K (Glassdoor est.),Group O is seeking a strong candidate with the...,3.1,Group O\n3.1,"Chicago, IL","Milan, IL",1001 to 5000 employees,1974,Company - Private,Staffing & Outsourcing,Business Services,$500 million to $1 billion (USD),-1,-1
761,761,870,Data Scientist,$91K-$105K (Glassdoor est.),Title: Data Scientist\n\nLocation: Chicago or ...,4.0,Two95 International Inc.\n4.0,"Chicago, IL","Cherry Hill, NJ",1 to 50 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,$1 to $5 million (USD),-1,-1
782,782,891,Data Scientist,$31K-$56K (Glassdoor est.),Data Scientist\n6 Month Contract to hire\nElmh...,3.5,Medix\n3.5,"Elmhurst, IL","Chicago, IL",201 to 500 employees,2001,Company - Private,Staffing & Outsourcing,Business Services,$100 to $500 million (USD),-1,-1
798,798,907,Supply Chain/Data Analyst - Merchandising,$31K-$56K (Glassdoor est.),Global Retail organization looking to add (2) ...,3.4,Aerotek\n3.4,"Chicago, IL","Hanover, MD",5001 to 10000 employees,1983,Company - Private,Staffing & Outsourcing,Business Services,Unknown / Non-Applicable,-1,-1
809,809,918,Urgent Need - Data Analyst,$31K-$56K (Glassdoor est.),Kelly Services is seeking a Provider Analytics...,3.4,Kelly\n3.4,"Chicago, IL","Troy, MI",5001 to 10000 employees,1946,Company - Public,Staffing & Outsourcing,Business Services,$5 to $10 billion (USD),"Adecco, ManpowerGroup, Allegis Corporation",-1
813,813,922,Data Analyst,$39K-$81K (Glassdoor est.),Collaborate with the Data Governance capabilit...,3.9,"TEKsystems, Inc\n3.9","Chicago, IL","Hanover, MD",1001 to 5000 employees,1983,Subsidiary or Business Segment,Staffing & Outsourcing,Business Services,$2 to $5 billion (USD),"Capgemini, Slalom, Accenture",-1
818,818,927,Sr. Data Analyst,$39K-$81K (Glassdoor est.),"Title: Sr. Data Analyst\nLocation: Chicago, IL...",3.8,Mondo\n3.8,"Chicago, IL","New York, NY",51 to 200 employees,2000,Company - Private,Staffing & Outsourcing,Business Services,$100 to $500 million (USD),"Robert Half, Insight Global",-1
824,824,933,Data Analyst,$39K-$81K (Glassdoor est.),Job Description\nData Analyst\n\nDuration: 6+ ...,4.7,CRS Group\n4.7,"Chicago, IL","Itasca, IL",51 to 200 employees,1994,Company - Private,Staffing & Outsourcing,Business Services,$10 to $25 million (USD),-1,-1
857,857,966,Pharmacovgilance Scientist,$99K-$174K (Glassdoor est.),Title: Sr Pharmacovigilance Scientist\n\nLocat...,3.4,Kelly\n3.4,"Chicago, IL","Troy, MI",5001 to 10000 employees,1946,Company - Public,Staffing & Outsourcing,Business Services,$5 to $10 billion (USD),"Adecco, ManpowerGroup, Allegis Corporation",-1
859,859,968,Data Engineer,$99K-$174K (Glassdoor est.),"Position: Data Engineer\nLocation: Bristol, CT...",3.8,Mondo\n3.8,"Chicago, IL","New York, NY",51 to 200 employees,2000,Company - Private,Staffing & Outsourcing,Business Services,$100 to $500 million (USD),"Robert Half, Insight Global",-1
865,865,974,Quantitative Researcher,$99K-$174K (Glassdoor est.),Job title: Quantitative Researcher\nJob type: ...,4.2,NJF Global Holdings\n4.2,"Chicago, IL","London, United Kingdom",51 to 200 employees,2003,Company - Private,Staffing & Outsourcing,Business Services,$10 to $25 million (USD),-1,TRUE
871,871,980,Data Engineer (AI/ML),$99K-$174K (Glassdoor est.),Mandatory Skills\nKnowledge and experience in ...,3.7,eTeam Inc.\n3.7,"Chicago, IL","South Plainfield, NJ",51 to 200 employees,1999,Company - Private,Staffing & Outsourcing,Business Services,$50 to $100 million (USD),"Artech Information Systems, Mindlance, Tech Ma...",-1
873,873,982,Data Analyst,$76K-$147K (Glassdoor est.),This position is responsible for working on mu...,2.7,TechUSA\n2.7,"Chicago, IL","Millersville, MD",1001 to 5000 employees,1998,Company - Private,Staffing & Outsourcing,Business Services,$100 to $500 million (USD),-1,-1
879,879,988,Data Analyst,$76K-$147K (Glassdoor est.),Job Description\nWe are seeking a Data Analyst...,4.1,SkySource Solutions\n4.1,"Downers Grove, IL","Berea, OH",1 to 50 employees,2017,Company - Public,Staffing & Outsourcing,Business Services,$5 to $10 million (USD),-1,-1
887,887,996,Machine Learning Engineer,$76K-$147K (Glassdoor est.),Job Description\nResponsibilities\n\nWe are lo...,-1.0,TalentCraft,"Chicago, IL","Oak Brook, IL",1 to 50 employees,2018,Company - Private,Staffing & Outsourcing,Business Services,Unknown / Non-Applicable,-1,-1
893,893,1002,Senior Data Scientist,$76K-$147K (Glassdoor est.),Job title: Senior Data Scientist\nJob type: Pe...,4.2,NJF Global Holdings\n4.2,"Chicago, IL","London, United Kingdom",51 to 200 employees,2003,Company - Private,Staffing & Outsourcing,Business Services,$10 to $25 million (USD),-1,TRUE
899,899,1008,Data Analyst,$76K-$147K (Glassdoor est.),Show expertise in data quality assurance\n\nEs...,4.5,Green Key Resources\n4.5,"Chicago, IL","New York, NY",201 to 500 employees,2004,Company - Private,Staffing & Outsourcing,Business Services,Unknown / Non-Applicable,"Beacon Hill Staffing Group, PageGroup, Solomon...",-1
916,916,1025,Data Engineer,$62K-$109K (Glassdoor est.),"Job Description\nHello,\n\nKani Solutions, Inc...",4.6,Kani Solutions\n4.6,"Chicago, IL","Princeton, NJ",201 to 500 employees,2009,Company - Private,Staffing & Outsourcing,Business Services,Unknown / Non-Applicable,-1,-1
943,943,1065,"Quantitative Researcher, Market Simulator",$70K-$123K (Glassdoor est.),"Job title: Quantitative Researcher, Market Sim...",4.2,NJF Global Holdings\n4.2,"Chicago, IL","London, United Kingdom",51 to 200 employees,2003,Company - Private,Staffing & Outsourcing,Business Services,$10 to $25 million (USD),-1,TRUE
945,945,1068,Talent Acquisition Vendor & Analytics Manager ...,$70K-$123K (Glassdoor est.),Job Details:\nConsult with senior business and...,3.4,PeopleReady\n3.4,"Chicago, IL","Tacoma, WA",5001 to 10000 employees,1989,Subsidiary or Business Segment,Staffing & Outsourcing,Business Services,$50 to $100 million (USD),"Randstad US, Labor Finders",-1
952,952,1078,Analytics Manager,$40K-$73K (Glassdoor est.),Job Description\nSmith Hanley Associates\nAnal...,4.5,Smith Hanley Associates\n4.5,"Chicago, IL","New York, 061",1 to 50 employees,1980,Company - Private,Staffing & Outsourcing,Business Services,Unknown / Non-Applicable,"Kforce, PageGroup, Robert Half",-1
975,975,1118,Data Analyst,$38K-$59K (Glassdoor est.),KellyMitchell matches the best IT and business...,3.6,Kelly Mitchell Group\n3.6,"Downers Grove, IL","Saint Louis, MO",1001 to 5000 employees,1998,Company - Private,Staffing & Outsourcing,Business Services,$50 to $100 million (USD),-1,-1

In [56]:
x = glassdoor_data['Industry'].value_counts()
x = x[:55]
x

-1                                          546
IT Services                                 472
Staffing & Outsourcing                      313
Biotech & Pharmaceuticals                   293
Computer Hardware & Software                264
Internet                                    238
Health Care Services & Hospitals            197
Consulting                                  166
Enterprise Software & Network Solutions     150
Investment Banking & Asset Management       109
Advertising & Marketing                      93
Insurance Carriers                           91
Colleges & Universities                      84
Accounting                                   64
Banks & Credit Unions                        64
Research & Development                       60
Federal Agencies                             57
Lending                                      41
Aerospace & Defense                          37
Video Games                                  30
Architectural & Engineering Services         25
TV Broadcast & Cable Networks                23
Electrical & Electronic Manufacturing        19
Insurance Agencies & Brokerages              18
Health, Beauty, & Fitness                    18
Department, Clothing, & Shoe Stores          18
Financial Analytics & Research               17
Brokerage Services                           17
Other Retail Stores                          17
Financial Transaction Processing             16
Health Care Products Manufacturing           16
Oil & Gas Services                           15
Construction                                 15
State & Regional Agencies                    15
Social Assistance                            14
Food & Beverage Manufacturing                13
Motion Picture Production & Distribution     12
Real Estate                                  12
Education Training Services                  12
Consumer Products Manufacturing              12
Wholesale                                    11
Energy                                       11
Telecommunications Services                  11
Transportation Equipment Manufacturing       11
Municipal Governments                        10
Industrial Manufacturing                      9
Cable, Internet & Telephone Providers         9
Grocery Stores & Supermarkets                 8
Logistics & Supply Chain                      8
Legal                                         7
Chemical Manufacturing                        7
Automotive Parts & Accessories Stores         6
Publishing                                    6
Casual Restaurants                            5
K-12 Education                                5
Name: Industry, dtype: int64

In [61]:
sal = glassdoor_data['Salary Estimate'].value_counts()
sal = sal[:55]
sal

$93K-$151K (Glassdoor est.)     62
$113K-$180K (Glassdoor est.)    61
$111K-$175K (Glassdoor est.)    60
$71K-$122K (Glassdoor est.)     60
$119K-$147K (Glassdoor est.)    44
$100K-$172K (Glassdoor est.)    37
$97K-$159K (Glassdoor est.)     32
$150K-$169K (Glassdoor est.)    31
$135K-$214K (Glassdoor est.)    31
$60K-$124K (Glassdoor est.)     31
$12K-$111K (Glassdoor est.)     31
$98K-$152K (Glassdoor est.)     31
$79K-$130K (Glassdoor est.)     30
$116K-$181K (Glassdoor est.)    30
$100K-$163K (Glassdoor est.)    30
$138K-$217K (Glassdoor est.)    30
$114K-$146K (Glassdoor est.)    30
$39K-$87K (Glassdoor est.)      30
$73K-$102K (Glassdoor est.)     30
$85K-$159K (Glassdoor est.)     30
$99K-$174K (Glassdoor est.)     30
$120K-$140K (Glassdoor est.)    30
$83K-$165K (Glassdoor est.)     30
$129K-$210K (Glassdoor est.)    30
$69K-$144K (Glassdoor est.)     30
$92K-$144K (Glassdoor est.)     30
$50K-$87K (Glassdoor est.)      30
$48K-$98K (Glassdoor est.)      30
$60K-$105K (Glassdoor est.)     30
$74K-$129K (Glassdoor est.)     30
$93K-$149K (Glassdoor est.)     30
$31K-$56K (Glassdoor est.)      30
$64K-$97K (Glassdoor est.)      30
$102K-$164K (Glassdoor est.)    30
$112K-$178K (Glassdoor est.)    30
$55K-$113K (Glassdoor est.)     30
$52K-$94K (Glassdoor est.)      30
$73K-$136K (Glassdoor est.)     30
$62K-$109K (Glassdoor est.)     30
$51K-$79K (Glassdoor est.)      30
$44K-$80K (Glassdoor est.)      30
$61K-$94K (Glassdoor est.)      30
$39K-$86K (Glassdoor est.)      30
$98K-$160K (Glassdoor est.)     30
$74K-$124K (Glassdoor est.)     30
$83K-$154K (Glassdoor est.)     30
$134K-$210K (Glassdoor est.)    30
$62K-$112K (Glassdoor est.)     30
$73K-$111K (Glassdoor est.)     30
$84K-$156K (Glassdoor est.)     30
$12K-$112K (Glassdoor est.)     30
$39K-$69K (Glassdoor est.)      30
$43K-$76K (Glassdoor est.)      30
$82K-$129K(Employer est.)       30
$39K-$81K (Glassdoor est.)      30
Name: Salary Estimate, dtype: int64

In [64]:
title = glassdoor_data ['Job Title'].value_counts()
title = title [:55]
title

Data Scientist                                                   274
Data Engineer                                                    260
Data Analyst                                                     246
Senior Data Scientist                                             91
Machine Learning Engineer                                         47
Senior Data Analyst                                               47
Big Data Engineer                                                 41
Business Intelligence Analyst                                     39
Senior Data Engineer                                              37
Lead Data Scientist                                               23
Sr. Data Scientist                                                23
Research Scientist                                                22
Data Modeler                                                      17
Junior Data Analyst                                               15
Principal Data Scientist                                          15
Statistician (Data Scientist) *12 month Roster* *Direct Hire*     14
Sr. Data Engineer                                                 13
Scientist                                                         13
Federal - Data Scientist                                          13
Business Data Analyst                                             11
Sr. Data Analyst                                                  11
Data Scientist - Nationwide Opportunities                         11
Quantitative Researcher                                           10
Quantum Data Scientist (Industrial-Process sector)                10
Quantum Principal Data Scientist (Industrial-Discrete sector)     10
Quantum Principal Data Scientist (Industrial-Process sector)      10
Principal Data Scientist- Public Sector                            9
Sr Data Scientist                                                  9
Microsoft Dynamics CRM Data Analyst                                9
Microsoft Analytics Consultant                                     9
Federal - Data Engineer - Senior                                   8
Data Engineer II                                                   8
Data Analyst III                                                   8
Lead Data Analyst                                                  8
Quantitative Analyst                                               8
Analytics Consultant                                               7
Bioinformatics Scientist                                           7
Senior Big Data Engineer                                           7
Computer Scientist                                                 7
Data Scientist II                                                  6
Data Architect II                                                  6
Scientist III (Molecular Biology)                                  6
COMPUTER SCIENTIST                                                 6
Sr Data Analyst                                                    6
Cloud Data Engineer                                                6
Principal Data Engineer                                            6
Machine Learning Scientist                                         6
Data Analyst II                                                    6
Physical Scientist                                                 6
Data Analyst I                                                     6
Marketing Data Analyst                                             5
Data Architect                                                     5
Data Analyst Junior                                                5
Data Science Manager                                               5
Senior Data Scientist - Nationwide Opportunities                   5
Name: Job Title, dtype: int64

In [67]:
city = glassdoor_data['Location'].value_counts()
city = city [:96]
city 
# Take total states
# Top cities

Austin, TX                   345
Chicago, IL                  330
San Diego, CA                304
New York, NY                 303
Houston, TX                  219
Philadelphia, PA             210
Los Angeles, CA              206
Dallas, TX                   180
San Antonio, TX              177
Phoenix, AZ                  165
Columbus, OH                 152
Irving, TX                   124
San Jose, CA                 105
Jacksonville, FL              68
Santa Clara, CA               65
Plano, TX                     60
Tempe, AZ                     49
Mountain View, CA             40
Sunnyvale, CA                 35
Fort Worth, TX                33
Palo Alto, CA                 33
Scottsdale, AZ                32
Redwood City, CA              32
Chandler, AZ                  27
Menlo Park, CA                26
Burbank, CA                   24
El Segundo, CA                22
La Jolla, CA                  22
Santa Monica, CA              21
Arlington, TX                 17
Culver City, CA               14
West Point, PA                13
Collegeville, PA              12
Richardson, TX                11
Malvern, PA                   11
King of Prussia, PA           11
Wilmington, DE                10
Pasadena, CA                  10
Conshohocken, PA               9
Fort Sam Houston, TX           8
Glendale, CA                   8
Cupertino, CA                  8
Lewisville, TX                 8
Northbrook, IL                 8
Fremont, CA                    8
Jersey City, NJ                7
DC Ranch, AZ                   7
Slough, OH                     7
Dublin, OH                     6
Camden, NJ                     6
Fort Washington, PA            6
Round Rock, TX                 6
Spring House, PA               6
Woodland Hills, CA             6
Irwindale, CA                  6
Brooklyn, NY                   6
Glendale, AZ                   5
Mesa, AZ                       5
Torrance, CA                   5
Grapevine, TX                  5
Lackland AFB, TX               5
Downers Grove, IL              5
Newark, CA                     5
Plymouth Meeting, PA           4
Gilbert, AZ                    4
Horsham, PA                    4
San Carlos, CA                 4
Newark, NJ                     4
Livermore, CA                  4
Allen, TX                      4
Long Beach, CA                 4
Carrollton, TX                 4
Gahanna, OH                    4
Westlake, TX                   4
Pearland, TX                   4
Cherry Hill, NJ                4
Coppell, TX                    4
West Chester, PA               4
Stafford, TX                   4
Monrovia, CA                   3
Universal City, CA             3
Marina del Rey, CA             3
Pleasanton, CA                 3
Pasadena, TX                   3
Westerville, OH                3
Addison, TX                    3
Farmers Branch, TX             3
Newtown, PA                    3
Monterey Park, CA              3
Whittier, CA                   2
Oak Brook, IL                  2
Brentford, United Kingdom      2
Cerritos, CA                   2
Spring, TX                     2
Doylestown, PA                 2
Exton, PA                      2
Name: Location, dtype: int64